# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='rawData.proto',
    package='wg',
    syntax='proto2',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\rrawData.proto\x12\x02wg\"[\n\x07IoTData\x12\x0b\n\x03MId\x18\x01 \x01(\t\x12\x0c\n\x04IDur\x18\x02 \x01(\t\x12\x0c\n\x04IEnd\x18\x03 \x01(\x03\x12\x0c\n\x04PAvg\x18\x04 \x01(\x01\x12\x0b\n\x03\x45In\x18\x05 \x01(\x01\x12\x0c\n\x04\x45Out\x18\x06 \x01(\x01\"E\n\x07rawData\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\t\x12\x19\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x0b.wg.IoTData'
)


_IOTDATA = _descriptor.Descriptor(
    name='IoTData',
    full_name='wg.IoTData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='MId', full_name='wg.IoTData.MId', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='IDur', full_name='wg.IoTData.IDur', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='IEnd', full_name='wg.IoTData.IEnd', index=2,
            number=3, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='PAvg', full_name='wg.IoTData.PAvg', index=3,
            number=4, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='EIn', full_name='wg.IoTData.EIn', index=4,
            number=5, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='EOut', full_name='wg.IoTData.EOut', index=5,
            number=6, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=21,
    serialized_end=112,
)


_RAWDATA = _descriptor.Descriptor(
    name='rawData',
    full_name='wg.rawData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='hash', full_name='wg.rawData.hash', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='signature', full_name='wg.rawData.signature', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='data', full_name='wg.rawData.data', index=2,
            number=3, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=114,
    serialized_end=183,
)

_RAWDATA.fields_by_name['data'].message_type = _IOTDATA
DESCRIPTOR.message_types_by_name['IoTData'] = _IOTDATA
DESCRIPTOR.message_types_by_name['rawData'] = _RAWDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IoTData = _reflection.GeneratedProtocolMessageType('IoTData', (_message.Message,), {
    'DESCRIPTOR': _IOTDATA,
    '__module__': 'rawData_pb2'
    # @@protoc_insertion_point(class_scope:wg.IoTData)
})
_sym_db.RegisterMessage(IoTData)

rawData = _reflection.GeneratedProtocolMessageType('rawData', (_message.Message,), {
    'DESCRIPTOR': _RAWDATA,
    '__module__': 'rawData_pb2'
    # @@protoc_insertion_point(class_scope:wg.rawData)
})
_sym_db.RegisterMessage(rawData)


# @@protoc_insertion_point(module_scope)
